# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {E:/My Programs/VHDL/semester_project/semester_project.cache/wt} [current_project]
set_property parent.project_path {E:/My Programs/VHDL/semester_project/semester_project.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {e:/My Programs/VHDL/semester_project/semester_project.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {E:/My Programs/VHDL/semester_project/semester_project.srcs/sources_1/new/sum_elem.vhd}
  {E:/My Programs/VHDL/semester_project/semester_project.srcs/sources_1/new/spt.vhd}
  {E:/My Programs/VHDL/semester_project/semester_project.srcs/sources_1/new/mul1.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top mul1 -part xc7a100tcsg324-1


write_checkpoint -force -noxdef mul1.dcp

catch { report_utilization -file mul1_utilization_synth.rpt -pb mul1_utilization_synth.pb }
